name: timeee
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core: Necesario para usar Firebase en Flutter
  firebase_core: ^3.6.0

  # Cloud Firestore: Base de datos en tiempo real de Firebase
  cloud_firestore: ^5.4.4

  # Firebase Analytics: Para monitorear eventos en la app
  firebase_analytics: ^11.0.0

  # Cupertino Icons: Ãconos para aplicaciones estilo iOS
  cupertino_icons: ^1.0.8

  google_fonts: ^6.2.1

  flutter_svg: ^2.0.10+1

  firebase_auth: ^5.3.1

  google_sign_in: ^6.2.1

  flutter_facebook_auth: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/